name: Develop CD Pipeline
env:
  ACTIONS_RUNNER_DEBUG: true

on:
  push:
    branches: ['terraform-init']
  pull_request:
    
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: develop
    env:
      TF_VAR_aws_access_id: ${{ secrets.AWS_ACCESS_KEY }}
      TF_VAR_aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_aws_region: "us-east-1" # Specify the AWS Region you are using

    steps:
      - name: Echo
        run: |
          echo "$TF_VAR_aws_access_id"
          echo "$TF_VAR_aws_secret_access_key"

      - name: Checkout code
        uses: actions/checkout@v2

      # Assume IAM Role
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v1
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ env.AWS_REGION }}

      # Terraform Installation
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1

      # Terraform base AWS services deployment
      - name: Terraform Init
        run: |
          terraform init -backend-config="access_key=$TF_VAR_aws_access_id" -backend-config="secret_key=$TF_VAR_aws_secret_access_key"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
      
      - name: Terraform Plan
        run: |
          terraform plan

      - name: Terraform Apply
        run: |
          terraform apply -auto-approve
